TICKETS_URL = 'https://api.usedesk.ru/tickets'
SINGLE_TICKET_URL = 'https://api.usedesk.ru/ticket'
CHANNEL_VOCAB_URL = 'https://api.usedesk.ru/channels'
GET_AGENTS_URL = 'https://api.usedesk.ru/users'
TOKEN = 'your_access_token'
